spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/store?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
  servlet:
    multipart:
      max-request-size: 15MB
      max-file-size: 10MB

# Spring读取配置文件中的数据#${user.address.max-count}
user:
  address:
    max-count: 20